### ISSUE TITLE
There seem to be a styling conflict with Bootstrap dropdown styles

### ISSUE THREAD

**Issue by splashdust** [buberdds/angular-bootstrap-colorpicker#42]
When I implemented the colorpicker it would at first not become visible. I tracked the problem down to the position attribute of the .dropdown class being set to relative by Bootstrap.

This is from the sass debug output:

``` css
/* line 22, ../../app/bower_components/sass-bootstrap/lib/_dropdowns.scss */
.dropdown {
    position: relative;
}
```

My work around was to set position:absolute!important in my own css.
